"use client";

import { useEffect, useState } from "react";

type Guess = "ai" | "real";

type ImageCard = {
  id: string;
  kind: Guess;
  src: string;
  alt: string;
  title: string;
};

function createSvgDataUrl(
  background: string,
  accent: string,
  detail: string,
  label: string,
) {
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 900">
      <rect width="800" height="900" fill="${background}" />
      <rect x="40" y="40" width="720" height="820" rx="36" fill="${detail}" opacity="0.28" />
      <circle cx="240" cy="280" r="100" fill="${accent}" opacity="0.72" />
      <path d="M110 690C180 530 290 470 370 520C440 560 470 650 560 680C620 698 698 670 730 610V840H110Z" fill="${accent}" opacity="0.54" />
      <path d="M130 708L250 600L380 690L525 540L690 720" stroke="white" stroke-width="18" fill="none" stroke-linecap="round" />
      <text x="400" y="840" text-anchor="middle" font-size="44" font-family="Verdana, sans-serif" fill="white" opacity="0.95">${label}</text>
    </svg>
  `;

  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

const imageDeck: ImageCard[] = [
  {
    id: "ai-01",
    kind: "ai",
    src: createSvgDataUrl("#050816", "#7c3aed", "#1d4ed8", "AI SCENE"),
    alt: "An abstract neon city skyline generated by AI",
    title: "Neon Skyline",
  },
  {
    id: "real-01",
    kind: "real",
    src: createSvgDataUrl("#07130f", "#16a34a", "#0f766e", "REAL LANDSCAPE"),
    alt: "A lush mountain valley with a reflective lake",
    title: "Mountain Valley",
  },
  {
    id: "ai-02",
    kind: "ai",
    src: createSvgDataUrl("#1f0f1f", "#f43f5e", "#fb923c", "AI PORTRAIT"),
    alt: "A surreal portrait with glowing eyes created by AI",
    title: "Glow Portrait",
  },
  {
    id: "real-02",
    kind: "real",
    src: createSvgDataUrl("#0f172a", "#38bdf8", "#334155", "REAL CITY"),
    alt: "A rainy street scene with glowing storefronts",
    title: "Rainy Street",
  },
  {
    id: "ai-03",
    kind: "ai",
    src: createSvgDataUrl("#140f1f", "#facc15", "#a21caf", "AI DREAM"),
    alt: "A dreamlike floating island scene generated by AI",
    title: "Floating Island",
  },
  {
    id: "real-03",
    kind: "real",
    src: createSvgDataUrl("#171717", "#f5f5f4", "#52525b", "REAL CABIN"),
    alt: "A cozy cabin in the woods at dusk",
    title: "Cozy Cabin",
  },
];

function chooseNextImage(usedIds: string[]) {
  const available = imageDeck.filter((card) => !usedIds.includes(card.id));

  if (available.length === 0) {
    return imageDeck[Math.floor(Math.random() * imageDeck.length)];
  }

  return available[Math.floor(Math.random() * available.length)];
}

export default function GamePage() {
  const [currentImage, setCurrentImage] = useState<ImageCard | null>(() =>
    chooseNextImage([]),
  );
  const [usedImages, setUsedImages] = useState<string[]>([]);
  const [streak, setStreak] = useState(0);
  const [bestStreak, setBestStreak] = useState(0);
  const [gameOver, setGameOver] = useState(false);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    const savedBest = window.localStorage.getItem("ai-or-not-best-streak");
    if (savedBest) {
      setBestStreak(Number(savedBest));
    }
  }, []);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    window.localStorage.setItem("ai-or-not-best-streak", String(bestStreak));
  }, [bestStreak]);

  const startGame = () => {
    setGameOver(false);
    setUsedImages([]);
    setStreak(0);
    setCurrentImage(chooseNextImage([]));
  };

  const resetGame = () => {
    startGame();
  };

  const handleGuess = (guess: Guess) => {
    if (!currentImage || gameOver) {
      return;
    }

    if (guess === currentImage.kind) {
      const nextStreak = streak + 1;
      const nextUsedImages = [...usedImages, currentImage.id];

      setStreak(nextStreak);
      setBestStreak((currentBest) => Math.max(currentBest, nextStreak));
      setUsedImages(nextUsedImages);
      setCurrentImage(chooseNextImage(nextUsedImages));
      return;
    }

    setBestStreak((currentBest) => Math.max(currentBest, streak));
    setGameOver(true);
  };

  return (
    <main className="relative flex min-h-screen items-center justify-center bg-black px-4 py-6 text-center sm:px-6 lg:px-8">
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-neon-green/10 via-transparent to-neon-green/10" />
      <div className="cyber-grid absolute inset-0 opacity-70" />

      <section className="relative z-10 flex w-full max-w-[680px] flex-col items-center gap-4">
        <div className="flex w-full items-center justify-center">
          <h1 className="text-glow-neon text-base leading-relaxed text-neon-green sm:text-lg md:text-xl">
            AI or NOT?
            <br />
            THE GAME
          </h1>
        </div>

        <div className="flex w-full items-center justify-center gap-3">
          <div className="flex items-center gap-2 rounded border border-neon-green/40 bg-black/80 px-3 py-2 text-[10px] uppercase tracking-[0.25em] text-neon-green sm:text-xs">
            <span className="text-sm">🔥</span>
            <span>Current</span>
            <span className="ml-1 text-sm">{streak}</span>
          </div>
          <div className="flex items-center gap-2 rounded border border-neon-green/40 bg-black/80 px-3 py-2 text-[10px] uppercase tracking-[0.25em] text-neon-green sm:text-xs">
            <span className="text-sm">🏆</span>
            <span>Best</span>
            <span className="ml-1 text-sm">{bestStreak}</span>
          </div>
        </div>

        <div className="flex w-full justify-center">
          {currentImage ? (
            <div className="w-full overflow-hidden rounded border border-neon-green/30 bg-black/80 shadow-neon-strong">
              <img
                src={currentImage.src}
                alt={currentImage.alt}
                className="h-[55vh] min-h-[320px] max-h-[70vh] w-full object-cover"
              />
            </div>
          ) : null}
        </div>

        {gameOver ? (
          <div className="w-full rounded border border-neon-green/30 bg-black/80 p-5 text-center shadow-neon">
            <p className="text-[10px] uppercase tracking-[0.35em] text-neon-green/60">
              Game Over
            </p>
            <h2 className="mt-3 text-glow-neon text-lg text-neon-green">
              GAME OVER
            </h2>
            <div className="mt-4 space-y-2 text-[11px] text-neutral-300 sm:text-sm">
              <p>Current streak: {streak}</p>
            </div>
            <button
              type="button"
              onClick={resetGame}
              className="mt-6 w-full border-2 border-neon-green bg-neon-green px-6 py-3 text-sm text-black transition-all duration-200 hover:-translate-y-0.5 hover:bg-black hover:text-neon-green"
            >
              TRY AGAIN
            </button>
          </div>
        ) : (
          <div className="flex w-full flex-col gap-3 sm:flex-row sm:justify-center">
            <button
              type="button"
              onClick={() => handleGuess("ai")}
              className="w-full rounded border-2 border-neon-green bg-black px-5 py-4 text-sm text-neon-green transition-all duration-200 hover:-translate-y-0.5 hover:bg-neon-green hover:text-black sm:w-[280px]"
            >
              🤖 AI GENERATED
            </button>
            <button
              type="button"
              onClick={() => handleGuess("real")}
              className="w-full rounded border-2 border-neon-green bg-black px-5 py-4 text-sm text-neon-green transition-all duration-200 hover:-translate-y-0.5 hover:bg-neon-green hover:text-black sm:w-[280px]"
            >
              📷 REAL PHOTO
            </button>
          </div>
        )}
      </section>
    </main>
  );
}
